// Frontend logic for E-Governance Voting DApp using ethers.js + MetaMask

// 1. Paste your deployed contract address here after running the deploy script.
//    Example: const CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
const CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

// 2. Paste the ABI from artifacts/contracts/EGovernanceVoting.sol/EGovernanceVoting.json
//    (property `abi`) after you run `npx hardhat compile`.
const CONTRACT_ABI = [
  // Minimal subset of ABI needed by frontend.
  // For full demo, you can replace this with the full ABI generated by Hardhat.
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "admin",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "electionCount",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_description",
        "type": "string"
      },
      {
        "internalType": "string[]",
        "name": "_candidates",
        "type": "string[]"
      },
      {
        "internalType": "uint256",
        "name": "_startTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_endTime",
        "type": "uint256"
      }
    ],
    "name": "createElection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_electionId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_candidateIndex",
        "type": "uint256"
      }
    ],
    "name": "vote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_electionId",
        "type": "uint256"
      }
    ],
    "name": "finalizeElection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_electionId",
        "type": "uint256"
      }
    ],
    "name": "getElection",
    "outputs": [
      { "internalType": "string", "name": "name", "type": "string" },
      { "internalType": "string", "name": "description", "type": "string" },
      {
        "internalType": "string[]",
        "name": "candidates",
        "type": "string[]"
      },
      {
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "endTime",
        "type": "uint256"
      },
      { "internalType": "bool", "name": "finalized", "type": "bool" },
      {
        "internalType": "uint256",
        "name": "totalVotes",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_electionId",
        "type": "uint256"
      }
    ],
    "name": "getResults",
    "outputs": [
      {
        "internalType": "string[]",
        "name": "candidates",
        "type": "string[]"
      },
      {
        "internalType": "uint256[]",
        "name": "candidateVotes",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllElectionIds",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "ids",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "startTime",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "endTime",
        "type": "uint256"
      }
    ],
    "name": "ElectionCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "candidateIndex",
        "type": "uint256"
      }
    ],
    "name": "VoteCast",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      }
    ],
    "name": "ElectionFinalized",
    "type": "event"
  }
];

let provider;
let signer;
let contract;

function getElements() {
  return {
    connectButton: document.getElementById("connectButton"),
    currentAccount: document.getElementById("currentAccount"),
    contractAddressDisplay: document.getElementById("contractAddressDisplay"),
    createElectionBtn: document.getElementById("createElectionBtn"),
    createElectionStatus: document.getElementById("createElectionStatus"),
    electionsList: document.getElementById("electionsList"),
    refreshElectionsBtn: document.getElementById("refreshElectionsBtn"),
    electionName: document.getElementById("electionName"),
    electionDescription: document.getElementById("electionDescription"),
    electionCandidates: document.getElementById("electionCandidates"),
    startInMinutes: document.getElementById("startInMinutes"),
    durationMinutes: document.getElementById("durationMinutes")
  };
}

async function init() {
  const els = getElements();

  if (!window.ethereum) {
    els.currentAccount.textContent = "MetaMask not detected";
    els.connectButton.disabled = true;
    els.createElectionBtn.disabled = true;
    els.electionsList.textContent =
      "Please install MetaMask and connect to Hardhat localhost network.";
    return;
  }

  provider = new ethers.providers.Web3Provider(window.ethereum);
  els.contractAddressDisplay.textContent = CONTRACT_ADDRESS;

  els.connectButton.onclick = connectWallet;
  els.createElectionBtn.onclick = createElection;
  els.refreshElectionsBtn.onclick = loadElections;

  if (CONTRACT_ADDRESS && CONTRACT_ADDRESS.startsWith("0x")) {
    contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, provider);
  }

  if (window.ethereum.selectedAddress) {
    await connectWallet();
  }

  await loadElections();
}

async function connectWallet() {
  const els = getElements();
  try {
    await provider.send("eth_requestAccounts", []);
    signer = provider.getSigner();
    const address = await signer.getAddress();
    els.currentAccount.textContent = `Wallet: ${address.slice(
      0,
      6
    )}...${address.slice(-4)}`;

    if (CONTRACT_ADDRESS && CONTRACT_ADDRESS.startsWith("0x")) {
      contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer);
    }
  } catch (err) {
    console.error(err);
    els.currentAccount.textContent = "Wallet connection failed";
  }
}

async function createElection() {
  const els = getElements();

  if (!contract || !signer) {
    alert("Please connect MetaMask and set a valid contract address.");
    return;
  }

  const name = els.electionName.value.trim();
  const description = els.electionDescription.value.trim();
  const candidatesRaw = els.electionCandidates.value.trim();
  const startIn = parseInt(els.startInMinutes.value || "0", 10);
  const duration = parseInt(els.durationMinutes.value || "0", 10);

  if (!name || !description || !candidatesRaw) {
    alert("Fill all election fields.");
    return;
  }

  const candidates = candidatesRaw
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  if (candidates.length < 2) {
    alert("Please provide at least two candidate names.");
    return;
  }

  if (duration <= 0) {
    alert("Duration must be greater than 0 minutes.");
    return;
  }

  const nowSeconds = Math.floor(Date.now() / 1000);
  const startTime = nowSeconds + startIn * 60;
  const endTime = startTime + duration * 60;

  try {
    els.createElectionStatus.textContent = "Sending transaction...";
    const tx = await contract.createElection(
      name,
      description,
      candidates,
      startTime,
      endTime
    );
    await tx.wait();
    els.createElectionStatus.textContent =
      "Election created successfully on blockchain.";
    els.electionName.value = "";
    els.electionDescription.value = "";
    els.electionCandidates.value = "";
    await loadElections();
  } catch (err) {
    console.error(err);
    els.createElectionStatus.textContent = "Failed to create election.";
  }
}

async function loadElections() {
  const els = getElements();

  if (!contract) {
    els.electionsList.textContent =
      "Set CONTRACT_ADDRESS in main.js after deployment, then refresh.";
    return;
  }

  try {
    els.electionsList.textContent = "Loading from blockchain...";
    const ids = await contract.getAllElectionIds();
    if (!ids || ids.length === 0) {
      els.electionsList.textContent = "No elections created yet.";
      return;
    }

    const container = document.createElement("div");

    for (let i = 0; i < ids.length; i++) {
      const id = ids[i].toNumber ? ids[i].toNumber() : Number(ids[i]);
      const [
        name,
        description,
        candidates,
        startTime,
        endTime,
        finalized,
        totalVotes
      ] = await contract.getElection(id);

      const [candidateNames, candidateVotes] = await contract.getResults(id);

      const card = document.createElement("div");
      card.className = "border rounded-3 p-3 mb-3";

      const now = Math.floor(Date.now() / 1000);
      let status = "Upcoming";
      if (now >= startTime && now <= endTime) status = "Ongoing";
      else if (now > endTime) status = "Ended";

      const badgeClass =
        status === "Ongoing"
          ? "bg-success"
          : status === "Upcoming"
            ? "bg-warning text-dark"
            : "bg-secondary";

      card.innerHTML = `
        <div class="d-flex justify-content-between align-items-center mb-2">
          <div>
            <div class="small text-muted-soft">Election #${id}</div>
            <h3 class="h6 mb-0">${name}</h3>
          </div>
          <span class="badge ${badgeClass} badge-pill small">${status}</span>
        </div>
        <p class="small text-muted-soft mb-2">${description}</p>
        <div class="small text-muted-soft mb-2">
          <strong>Time window:</strong>
          ${new Date(startTime * 1000).toLocaleString()} &rarr;
          ${new Date(endTime * 1000).toLocaleString()}
        </div>
        <div class="small text-muted-soft mb-2">
          <strong>Total votes:</strong> ${totalVotes.toString()} |
          <strong>Finalized:</strong> ${finalized ? "Yes" : "No"}
        </div>
        <div class="mt-2" id="candidates-${id}"></div>
      `;

      const candidatesDiv = card.querySelector(`#candidates-${id}`);
      candidateNames.forEach((cand, index) => {
        const votesFor = candidateVotes[index];
        const line = document.createElement("div");
        line.className =
          "d-flex justify-content-between align-items-center small mb-1";
        line.innerHTML = `
          <span>${cand}</span>
          <span class="text-muted-soft">${votesFor.toString()} vote(s)</span>
        `;

        if (status === "Ongoing") {
          const voteBtn = document.createElement("button");
          voteBtn.className = "btn btn-sm btn-outline-light ms-2";
          voteBtn.textContent = "Vote";
          voteBtn.onclick = () => castVote(id, index);
          const right = document.createElement("div");
          right.className = "d-flex align-items-center";
          right.appendChild(line.children[0]);
          right.appendChild(voteBtn);

          const row = document.createElement("div");
          row.className =
            "d-flex justify-content-between align-items-center mb-1";
          row.appendChild(right);
          const votesSpan = document.createElement("span");
          votesSpan.className = "text-muted-soft small";
          votesSpan.textContent = `${votesFor.toString()} vote(s)`;
          row.appendChild(votesSpan);
          candidatesDiv.appendChild(row);
        } else {
          candidatesDiv.appendChild(line);
        }
      });

      container.appendChild(card);
    }

    els.electionsList.innerHTML = "";
    els.electionsList.appendChild(container);
  } catch (err) {
    console.error(err);
    els.electionsList.textContent = "Failed to load elections from blockchain.";
  }
}

async function castVote(electionId, candidateIndex) {
  if (!contract || !signer) {
    alert("Connect MetaMask first.");
    return;
  }

  try {
    const tx = await contract.vote(electionId, candidateIndex);
    await tx.wait();
    alert("Vote cast successfully!");
    await loadElections();
  } catch (err) {
    console.error(err);
    alert("Failed to cast vote. Check console for details.");
  }
}

window.addEventListener("DOMContentLoaded", init);

